# ---------------------------------------------------------------
# Theme Core Configuration Settings
# See: https://theme-next.org/docs/theme-settings/
#      https://github.com/amehime/hexo-theme-shoka/blob/master/_config.yml
# ---------------------------------------------------------------

# Alternate site name
alternate: Daniel Naranjo
open_graph:
  twitter_id: PompaDonpa
  #fb_admins:
  #fb_app_id:

# Assets
statics: / #//cdn.jsdelivr.net/gh/username/RepositoryName@latest/
css: css
js: js
images: images


# ---------------------------------------------------------------
# Site Information Settings
# See: https://theme-next.org/docs/getting-started/
# ---------------------------------------------------------------

favicon:
  apple_touch_icon: /favicon.png
  safari_pinned_tab: /logo.svg
  #android_manifest: /manifest.json
  #ms_browserconfig: /browserconfig.xml

# Dark Mode
# By default, the page judges whether to turn on the dark mode according to the device settings or user selection
# if `true`, the page will be displayed directly as Dark Mode, unless the user makes another choice
darkmode: false

# By default the page will automatically scroll to the last viewed position
# if `false`, automatic positioning will be turned off
auto_scroll: false

# Whether to show the loading cat
loader:
  start: false # When entering the page
  switch: true # When switching to another page

# click with Firework
fireworks:
  enable: true
  color:
    - "rgba(152, 186, 227, .9)"
    - "rgba(89, 129, 177, .9)"
    - "rgba(54, 84, 117, .9)"
    - "rgba(21, 39, 60, .9)"

font:
  enable: true
  # Font options:
  # `external: true` will load this font family from `host` above.
  # `family: Times New Roman`. Without any quotes.
  # `size: x.x`. Use `em` as unit. Default: 1 (16px)

  # Global font settings used for all elements inside <body>.
  global:
    external: true
    family: Mulish
    size:

  # Font settings for alternate title.
  logo:
    external: true
    family: Fredericka the Great
    size: 3.5

  # Font settings for site title.
  title:
    external: true
    family: Noto Serif JP
    size: 2.5

  # Font settings for headlines (<h1> to <h6>).
  headings:
    external: true
    family: Noto Serif SC
    size:

  # Font settings for posts.
  posts:
    external: true
    family:

  # Font settings for <code> and code blocks.
  codes:
    external: true
    family: Inconsolata

# project of https://www.iconfont.cn/
# //at.alicdn.com/t/font_1832207_c8i9n1ulxlt.css => 1832207_c8i9n1ulxlt
iconfont: "1832207_igi8uaupcus"

language_switcher : true

footer:
  # Specify the date when the site was setup. If not defined, current year will be used.
  since: 2020
  copyright: Yume Shoka
  icon:
    name: sakura rotate
    # Change the color of icon, using Hex Code.
    color: "#FAC863"
  # Dependencies: https://github.com/theme-next/hexo-symbols-count-time
  count: true
  powered: true


# ---------------------------------------------------------------
# Menu Settings
# ---------------------------------------------------------------

menu:
  home: / || home
  about: /about/ || user
  Contact : /contact/ || address-card
  posts:
    default: / || feather
    archives: /archives/ || list-alt
    categories: /categories/ || th
    Code: /code/ || paw
    Resources : /resources/ || sitemap
    tags: /tags/ || tags
  Projects: /projects/ || flag
  Stock Footage : /stock/ || eye
  WebStack: /webstack/ || magic
  WhiteBoard : /whiteboard/ || zhihu


# ---------------------------------------------------------------
# Sidebar Settings
# ---------------------------------------------------------------
# Social Links
# Usage: `Key: permalink || icon || color`
# Key is the link label showing to end users.
# Value before `||` delimiter is the target permalink,
# secend value is the name of Font icon.
# ---------------------------------------------------------------

social:
  github: https://github.com/PompaDonpa || github || "#191717"
  twitter: https://twitter.com/PompaDonpa || twitter || "#00aff0"
  #music: https://music.163.com/#/user/home?id=yourid || cloud-music || "#e60026"
  about: https://about.me/PompaDonpa || address-card || "#3b5998"
  #email: mailto:PompaDonpa@mail.com || envelope || "#55acd5"
  #facebook: https://www.facebook.com/PompaDonpa || facebook
  stackoverflow: https://stackoverflow.com/PompaDonpa || stack-overflow || "#F99157"
  youtube: https://youtube.com/PompaDonpa || youtube || "#EC5f67"
  instagram: https://instagram.com/PompaDonpa || instagram || "#E1306C"
  #skype: skype:PompaDonpa?call|chat || skype
  #twitch: https://www.twitch.tv/pompadonpa || 


# Sidebar
sidebar:
  # Sidebar Position.
  # position: left
  position: right
  # Replace the default avatar image and set the url here.
  avatar: avatar.jpg


#Widgets
widgets:
  # if true, will show random posts
  random_posts: true
  # if true, will show recent comments
  recent_comments: true


# ---------------------------------------------------------------
# POST Settings
# ---------------------------------------------------------------

post:
  # Dependencies: https://github.com/theme-next/hexo-symbols-count-time
  count: true

# Reward (Donate)
reward:
  # If true, reward will be displayed in every article by default.
  enable: true
  account:
    Ethereum: /ethereum.png
    Paypal: /paypal.png
    Bitcoin: /bitcoin.png

# TagCloud settings for tags page.
tagcloud:
  # All values below are same as default, change them by yourself.
  min: 22 # Minimun font size in px
  max: 36 # Maxium font size in px
  start: "#72cecf" # Start color (hex, rgba, hsla or color keywords)
  end: "#ffbac3" # End color (hex, rgba, hsla or color keywords)
  amount: 200 # Amount of tags, change it if you have more than 200 tags



# ---------------------------------------------------------------
# Third Party Plugins & Services Settings
# ---------------------------------------------------------------

# Creative Commons 4.0 International License.
# See: https://creativecommons.org/share-your-work/licensing-types-examples
# Available values of license: by | by-nc | by-nc-nd | by-nc-sa | by-nd | by-sa | zero
# You can set a language value if you prefer a translated version of CC license, e.g. deed.zh
# CC licenses are available in 39 languages, you can find the specific and correct abbreviation you need on https://creativecommons.org
creative_commons:
  license: by-nc-sa
  language: 



# Comments
# Valine
# For more information: https://github.com/amehime/MiniValine
valine:
  appId: AawwbH8AvSt9fvvd5gTLSmfO-MdYXbMMI
  appKey: q6VhPeT4rOtjOqPdFhtHlAla
  placeholder: "\tIf you don't believe in God, then the God concept is \n\ta great placeholder for everything we don't know,\n\twhich is exponentially more than we do know.\n\n\t\t\t\t\t\t\t\t - Bryant McGill"
  avatar: mm # Gravatar style : mp, identicon, monsterid, wavatar, robohash, retro
  avatarForce : true
  emojiCDN : '//cdn.jsdelivr.net/gh/zhheo/Sticker-Heo@latest/Sticker-100/'
  pageSize: 10 # Pagination size
  lang: en
  visitor: true # Article reading statistic
  NoRecordIP: false # Whether to record the commenter IP
  serverURLs: # When the custom domain name is enabled, fill it in here (it will be detected automatically by default, no need to fill in)
  powerMode: true
  tagMeta:
    visitor: Nanashi
    master: Shogun
    friend:
    investor: Munehisa Homma
  tagColor:
    master: "var(--color-orange)"
    friend: "var(--color-aqua)"
    investor: "var(--color-pink)"
  tagMember:
    master:
      # - hash of master@email.com
      # - hash of master2@email.com
    friend:
      # - hash of friend@email.com
      # - hash of friend2@email.com
    investor:
      # - hash of investor1@email.com

# bgm
audio:
  - title: OverTime
    list:
     - https://music.163.com/#/playlist?id=2943811283
     - https://music.163.com/#/playlist?id=2297706586
  - title: Overturned
    list:
     - https://music.163.com/#/playlist?id=2031842656

# random image api
image_server: # "https://acg.xydwz.cn/api/api.php"
# image_server: "https://images"

# Algolia Search
# For more information: https://www.algolia.com
search:
  hits:
    per_page: 10

# Dependencies: https://github.com/amehime/hexo-renderer-multi-markdown-it
pangu: true

# Quicklink Support
# For more information: https://github.com/GoogleChromeLabs/quicklink
quicklink:
  # Custom a time in milliseconds by which the browser must execute prefetching.
  timeout: 3000
  # Default (true) will attempt to use the fetch() API if supported (rather than link[rel=prefetch]).
  priority: true

  # For more flexibility you can add some patterns (RegExp, Function, or Array) to ignores.
  # See: https://github.com/GoogleChromeLabs/quicklink#custom-ignore-patterns
  ignores:

# ---------------------------------------------------------------
# analytics & SEO Settings
# ---------------------------------------------------------------
baidu_analytics: # <app_id>

# Disable Baidu transformation on mobile devices.
disable_baidu_transformation: true

# Automatically add external URL with Base64 encrypt & decrypt.
exturl: true

# Google Webmaster tools verification.
# See: https://www.google.com/webmasters
google_site_verification:

# Bing Webmaster tools verification.
# See: https://www.bing.com/webmaster
bing_site_verification:


#! ---------------------------------------------------------------
#! DO NOT EDIT THE FOLLOWING `vendors` SETTINGS
#! UNLESS YOU KNOW WHAT YOU ARE DOING
#! Script dependencies will be combined with jsDelivr (cdn.jsdelivr.net)
#! ---------------------------------------------------------------
vendors:
  css:
    katex: npm/katex@0.12.0/dist/katex.min.css
    comment: css/comment.css
    fancybox: combine/npm/@fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css,npm/justifiedGallery@3.8.1/dist/css/justifiedGallery.min.css
  js:
    pace: npm/pace-js@1.0.2/pace.min.js
    pjax: npm/pjax@0.2.8/pjax.min.js
    fetch: npm/whatwg-fetch@3.4.0/dist/fetch.umd.min.js
    anime: npm/animejs@3.2.0/lib/anime.min.js
    algolia: npm/algoliasearch@4/dist/algoliasearch-lite.umd.js
    instantsearch: npm/instantsearch.js@4/dist/instantsearch.production.min.js
    lazyload: npm/lozad@1/dist/lozad.min.js
    quicklink: npm/quicklink@2/dist/quicklink.umd.js
    fancybox: combine/npm/jquery@3.5.1/dist/jquery.min.js,npm/@fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js,npm/justifiedGallery@3.8.1/dist/js/jquery.justifiedGallery.min.js
    valine: gh/amehime/MiniValine@4.2.2-beta10/dist/MiniValine.min.js
    copy_tex: npm/katex@0.12.0/dist/contrib/copy-tex.min.js
    chart: npm/frappe-charts@1.5.0/dist/frappe-charts.min.iife.min.js
